apiVersion: v1
kind: Service
metadata:
  name: live-streaming
spec:
  type: LoadBalancer
  ports:
  - name: rtmp
    port: 1935
    targetPort: 1935
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: live-streaming