apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rtmp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-rtmp
  template:
    metadata:
      labels:
        app: nginx-rtmp
    spec:
      containers:
      - name: nginx-rtmp
        image: acrapp1m1a.azurecr.io/nginx-rtmp
        ports:
        - containerPort: 1935
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-rtmp
spec:
  type: LoadBalancer
  ports:
  - port: 1935
    targetPort: 1935
    protocol: TCP
    name: rtmp
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx-rtmp